import { StyleSheet } from "react-native";
import { COLORS, SIZES, TEXT } from "../../constants/theme";

const styles = StyleSheet.create({
  textContainer: {
    alignItems: "center",
    width: 247,
    height: 151,
    position: "absolute",
    top: 116,
    left: 64,
    gap: 15,
  },
  title: {
    fontFamily: "Bold",
    fontSize: 40,
    fontWeight: "700",
    lineHeight: 56,
    letterSpacing: 0,
    textAlign: "center",
    width: 247,
    height: 112,
  },
  formContainer: {
    backgroundColor: "white",
    width: 340,
    height: 328,
    position: "absolute",
    top: 420,
    borderRadius: 24,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: -9,
    },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 20,
    justifyContent: "space-between",
  },
  inputWrapper: {
    marginBottom: 16,
  },
  input: {
    fontSize: 16,
    marginBottom: 8,
    color: COLORS.black,
  },
  inputContainer: {
    borderWidth: 1,
    borderColor: COLORS.gray,
    borderRadius: 4,
    padding: 8,
  },
  forgetPass: {
    fontFamily: "SemiBold",
    color: COLORS.black,
    marginTop: 10,
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
  },
  goBackContainer: {
    position: "absolute",
    top: 54,
    left: 26,
    zIndex: 999,
  },
  imageBackgroundContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 200,
  },
  imageBackground: {
    height: "100%",
    width: "100%",
    borderRadius: 20,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    overflow: "hidden",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  authContent: {
    padding: 20,
  },
  switchAuthContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginVertical: 22,
    top: 130,
  },
  switchAuthText: {
    fontSize: 16,
    color: COLORS.black,
    fontWeight: "300",
  },
  switchAuthLink: {
    fontSize: 16,
    color: COLORS.secondary,
    fontWeight: "700",
    marginLeft: 6,
  },
  buttons: {
    marginTop: 8,
  },
  orContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: "#E5E5E5",
  },
  orText: {
    fontFamily: "SemiBold",
    marginHorizontal: 10,
    color: "#5A5A5A",
    fontWeight: 300,
    fontSize: 16,
    lineHeight: 19.36,
  },
  privacyTextContaner: {
    fontFamily: "SemiBold",
    width: 300,
    opacity: 0.8,
    marginTop: 25,
    marginLeft: 5,
  },
  privacyText: {
    fontWeight: "500",
    fontSize: 14,
    color: "gray",
    lineHeight: 20,
  },
  policyLink: {
    fontFamily: "SemiBold",
    color: COLORS.secondary,
    marginRight: 5,
    marginLeft: 5,
  },
  passformContainer: {
    backgroundColor: "white",
    width: 340,
    position: "absolute",
    top: 470,
    borderRadius: 24,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: -9,
    },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 20,
    justifyContent: "space-between",
  },
});

export default styles;
